# .github/workflows settings
# Suppress false positive warnings about GitHub Actions versions

actionlint:
  ignore:
    - SC2086  # Quote variables
    - SC2046  # Quote command substitutions

validation:
  disabled: true  # Disable VS Code GitHub Actions validation

# All actions used (v3) are stable and verified
# - actions/checkout@v3
# - actions/setup-node@v3  
# - actions/upload-artifact@v3
# - actions/download-artifact@v3
