name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - rohinqaderyan

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What actually happened instead?
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser(s)
      description: Which browser(s) are you seeing this on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Any relevant environment information
      placeholder: |
        - OS: [e.g., Windows 11, macOS Ventura]
        - Browser Version: [e.g., Chrome 120]
        - Screen Size: [e.g., 1920x1080]

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop screenshots here

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: Any relevant console errors or logs
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have tried clearing my browser cache and cookies
        - label: I can consistently reproduce this bug
